### ISSUE TITLE
LLVM Caching `save-state` deprecated

### ISSUE THREAD

**Issue by AjaniBilby** [KyleMayes/install-llvm-action#36]
I'm getting a warning saying:
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
[Deprecation Notice](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

From my understanding this is something that needs to be fixed as part of the action, and not something I can configured.
Though I could be wrong.

**Comment by AjaniBilby** [comment]
Context of my build action in case it influences this
```yml
# ....
jobs:
  build-linux:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      # ...

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: "./lib/install"
          key: llvm-14.0

      - name: "Install LLVM and Clang"
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
          directory: "./lib/install"

      - name: Symlink libclang.so (Linux)
        run: sudo ln -s libclang-14.so.1 /lib/x86_64-linux-gnu/libclang.so
        working-directory: ${{ env.LLVM_PATH }}/lib
      # ....
```

**Comment by KyleMayes** [comment]
I'm pretty sure this was fixed at some point when I upgraded the `@actions/core` version used by this action.

**Comment by AjaniBilby** [comment]
Is that change live?
Because it doesn't appear to have completely fixed the issue.

Previously my Github actions wouldn't even load from cache, which they are at least now, however I'm still getting the deprecation warning. ([action log](https://github.com/qupa-project/uniview-lang/actions/runs/4020290057/jobs/6908042988#step:5:17))

**Comment by KyleMayes** [comment]
Oh, maybe this is caused by the caching.
I'll take another look.

**Comment by AjaniBilby** [comment]
The issue specifically appears to be in relation to using `actions/cache@v2`, if you replace it with `actions/cache@v3` it appears to work perfectly.

However it appears that `install-llvm-action` isn't properly detecting when the cache is found with `v3`. i.e. [165](https://github.com/qupa-project/uniview-lang/actions/runs/4320694491/jobs/7541174007) -> [166](https://github.com/qupa-project/uniview-lang/actions/runs/4320715678/jobs/7541216042)

**Comment by AjaniBilby** [comment]
It appears v2 was also possibly not detecting the cache load correctly either [164](https://github.com/qupa-project/uniview-lang/actions/runs/4320488292/jobs/7540785482)

**Comment by KyleMayes** [comment]
Looking at your workflow file (https://github.com/qupa-project/uniview-lang/actions/runs/4320715678/workflow), you are missing the `cached` option for this action.

I updated the example in the `README.md` to use v3, it now looks like this:

```yaml
- name: Cache LLVM and Clang
  id: cache-llvm
  uses: actions/cache@v3
  with:
    path: |
      C:/Program Files/LLVM
      ./llvm
    key: llvm-3.5
- name: Install LLVM and Clang
  uses: KyleMayes/install-llvm-action@v1
  with:
    version: "3.5"
    cached: ${{ steps.cache-llvm.outputs.cache-hit }}
```

The `cached` option is necessary to inform this action that it should use the cached values.

I added a workflow to this repository to check the caching and it seems to work fine with `actions/cache@v3`. For example, you can see this action using the cache here: https://github.com/KyleMayes/install-llvm-action/actions/runs/4548947844/jobs/8020511525

**Comment by AjaniBilby** [comment]
Confirmed this solved the problem on uniview-lang/action-[\#173](https://github.com/qupa-project/uniview-lang/actions/runs/4559901699/jobs/8044318423)
